// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiqxote.databaseqxote;

#nullable disable

namespace apiqxote.Migrations
{
    [DbContext(typeof(DatabaseqxoteContext))]
    partial class DatabaseqxoteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apiqxote.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("Abudance")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("abudance");

                    b.Property<int?>("CloudCover")
                        .HasColumnType("int")
                        .HasColumnName("cloud_cover");

                    b.Property<string>("Coordinates")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)")
                        .HasColumnName("coordinates");

                    b.Property<string>("Coverboards")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("coverboards");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<string>("SpeciesName")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("species_name");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float")
                        .HasColumnName("temperature");

                    b.Property<int?>("WindSpeed")
                        .HasColumnType("int")
                        .HasColumnName("wind_speed");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("zone");

                    b.HasKey("AnimalId");

                    b.HasIndex(new[] { "Zone" }, "fk_animal_zone1");

                    b.ToTable("animal", (string)null);
                });

            modelBuilder.Entity("apiqxote.Models.BioConcentration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Bcf")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("bcf");

                    b.Property<decimal?>("Cf")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cf");

                    b.Property<decimal?>("Ctree")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ctree");

                    b.Property<decimal?>("R")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("r");

                    b.Property<string>("Species")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("species");

                    b.HasKey("Id");

                    b.ToTable("bio_concentration", (string)null);
                });

            modelBuilder.Entity("apiqxote.Models.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<string>("Coordinate")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)")
                        .HasColumnName("coordinate");

                    b.Property<string>("Cover")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("cover");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<float?>("Humidity")
                        .HasColumnType("real")
                        .HasColumnName("humidity");

                    b.Property<string>("PlotNr")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("plot_nr");

                    b.Property<string>("Species")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("species");

                    b.Property<string>("Temperature")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("temperature");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("zone");

                    b.HasKey("PlantId");

                    b.HasIndex(new[] { "Zone" }, "fk_plant_zone1");

                    b.ToTable("plant", (string)null);
                });

            modelBuilder.Entity("apiqxote.Models.Tree", b =>
                {
                    b.Property<int>("TreeNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tree_nr");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreeNr"));

                    b.Property<string>("Zone")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("zone");

                    b.Property<int>("BioConcentrationId")
                        .HasColumnType("int")
                        .HasColumnName("bio_concentration_id");

                    b.Property<decimal?>("Circumference")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("circumference");

                    b.Property<string>("Coordinate")
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)")
                        .HasColumnName("coordinate");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("height");

                    b.Property<string>("TreeName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("tree_name");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("volume");

                    b.HasKey("TreeNr", "Zone");

                    b.HasIndex(new[] { "BioConcentrationId" }, "fk_tree_bio_concentration1");

                    b.HasIndex(new[] { "TreeName" }, "fk_tree_tree_name1");

                    b.HasIndex(new[] { "Zone" }, "fk_tree_zone1");

                    b.ToTable("tree", (string)null);
                });

            modelBuilder.Entity("apiqxote.Models.TreeName", b =>
                {
                    b.Property<string>("TreeName1")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("tree_name");

                    b.Property<int?>("CoordinateCount")
                        .HasColumnType("int")
                        .HasColumnName("coordinate_count");

                    b.HasKey("TreeName1");

                    b.ToTable("tree_name", (string)null);
                });

            modelBuilder.Entity("apiqxote.Models.Zone", b =>
                {
                    b.Property<string>("Zone1")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("zone");

                    b.Property<int?>("Area")
                        .HasColumnType("int")
                        .HasColumnName("area");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("classification");

                    b.Property<int?>("Plots")
                        .HasColumnType("int")
                        .HasColumnName("plots");

                    b.HasKey("Zone1");

                    b.ToTable("zone", (string)null);
                });

            modelBuilder.Entity("apiqxote.Models.Animal", b =>
                {
                    b.HasOne("apiqxote.Models.Zone", "ZoneNavigation")
                        .WithMany("Animals")
                        .HasForeignKey("Zone")
                        .IsRequired()
                        .HasConstraintName("fk_animal_zone1");

                    b.Navigation("ZoneNavigation");
                });

            modelBuilder.Entity("apiqxote.Models.Plant", b =>
                {
                    b.HasOne("apiqxote.Models.Zone", "ZoneNavigation")
                        .WithMany("Plants")
                        .HasForeignKey("Zone")
                        .IsRequired()
                        .HasConstraintName("fk_plant_zone1");

                    b.Navigation("ZoneNavigation");
                });

            modelBuilder.Entity("apiqxote.Models.Tree", b =>
                {
                    b.HasOne("apiqxote.Models.BioConcentration", "BioConcentration")
                        .WithMany("Trees")
                        .HasForeignKey("BioConcentrationId")
                        .IsRequired()
                        .HasConstraintName("fk_tree_bio_concentration1");

                    b.HasOne("apiqxote.Models.TreeName", "TreeNameNavigation")
                        .WithMany("Trees")
                        .HasForeignKey("TreeName")
                        .IsRequired()
                        .HasConstraintName("fk_tree_tree_name1");

                    b.HasOne("apiqxote.Models.Zone", "ZoneNavigation")
                        .WithMany("Trees")
                        .HasForeignKey("Zone")
                        .IsRequired()
                        .HasConstraintName("fk_tree_zone1");

                    b.Navigation("BioConcentration");

                    b.Navigation("TreeNameNavigation");

                    b.Navigation("ZoneNavigation");
                });

            modelBuilder.Entity("apiqxote.Models.BioConcentration", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("apiqxote.Models.TreeName", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("apiqxote.Models.Zone", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Plants");

                    b.Navigation("Trees");
                });
#pragma warning restore 612, 618
        }
    }
}
